### ISSUE TITLE
Ay, cringelord

### ISSUE THREAD

**Issue by Zayveeo5e** [Titanfall2-T/LiteralAimbot#1]
Get my mod page off of your badly made attempt at an aimbot, Time.

**Comment by Titanfall2-T** [comment]
> Get my mod page off of your badly made attempt at an aimbot, Time.

This is literally my mod, there are 100s of messages mentioning how I was the one who originally made it dum dum.

If it's really yours send all the mod icons that it has used in the past when posted on Thunderstore, including the original. xD

**Comment by Titanfall2-T** [comment]
Nah I'm good lol

**Comment by Zayveeo5e** [comment]
Mans really thought I meant the god-awful AMM mod and then edited his response when he realized.

**Comment by Titanfall2-T** [comment]
> Mans really thought I meant the god-awful AMM mod and then edited his response when he realized.

No I thought you meant the aimbot, man you're really dumb lol
